apiVersion: v1
kind: Pod
metadata:
  name: hpcc
spec:  # specification of the pod’s contents
  restartPolicy: Never
  containers:
  - name: hpcc-trusty
    image: "hpccsystems/platform-ce:5.4.8-1trusty"
    ports:
       - containerPort: 8010
