apiVersion: v1
kind: ReplicationController
metadata:
  name: roxie-controller
spec:
  replicas: 1
  selector:
    app: roxie
  template:
    metadata:
      labels:
        app: roxie
    spec:
      containers:
      - name: roxie
        image: "hpccsystems/platform-ce:5.4.8-1trusty"
