apiVersion: v1
kind: ReplicationController
metadata:
  name: thor-controller
spec:
  replicas: 2
  selector:
    app: thor
  template:
    metadata:
      labels:
        app: thor
    spec:
      containers:
      - name: thor
        image: "hpccsystems/platform-ce:5.4.8-1trusty"
